# Labeler labels incoming pull requests.
name: "Labeler"
on:
  workflow_dispatch:


jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      if: github.base_ref == null
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
